<?php

/**
 * Test class for WebSession.
 * Generated by PHPUnit on 2012-02-18 at 13:38:04.
 */
class WebSessionTest extends PHPUnit_Framework_TestCase {

    /**
     * Sets environment for all tests
     */
    public static function setUpBeforeClass() {
        // start pocket-knife
        $path = dirname(dirname(dirname(__FILE__)));
        require $path . '/start.php';
        // manually load classes
        autoload('BasicClass');
        BasicClass::autoloadAll('WebSession');
    }

    /**
     * Demonstrates WebSession funtionality
     */
    public function testStorage() {
        WebSession::put('a', 42);
        $expected = 42;
        $actual = WebSession::get('a');
        $this->assertEquals($expected, $actual);
        echo session_id();
    }

}